# Site settings
title: Edwin Heredia
twitter_username: 
name: Edwin Heredia

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 #- title: Blog
 #  url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/edwinhere72
 #- title: StackOverflow
 #  url: https://stackoverflow.com/users/258813/rhinds
 #- title: DZone
 #  url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/edwin-heredia-3029b819/

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.NET MVC
 - .NET technology
 - Entity Framework
 - Restful Web Apis
 - WCF
 - SOAP
 - HTML5
 - CSS3
 - Bootstrap
 - JavaScript
 - Angular JS
 - Node JS
 - React JS
 - Java
 - PHP
 - SQL Server
 - Database Design
 - DevOps CI/CD
 - AWS
 - Azure 
 - Docker 
 - Kubernetes
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Application Development Supervisor
   start: 2018
   end: Ongoing
   employer: DCYF
   description: 
      •	Currently leading 10 software developers that includes 3 agile development teams. </br>
      •	Provide technical leadership to the development team of agile software developers to create, maintain, and enhance diverse 
        software application system </br>
      •	Work closely with the Product/Business teams in defining the software development plan in meeting the product vision </br>
      •	Coordinate with various business units and determined priority for projects and analyzed resources required. </br>
      •	Ability to build prototype software using modern programming language such as C#, .NET MVC, Entity Framework, Java, JavaScript, JQuery, Bootstrap. </br>
      •	Design, develop, and maintain full-stack web applications on AWS; heavy focus on RESTful APIs with automate deployment DevOps using TFS, Octopus Deploy, Redgate SQL for Database. </br>
      •	Design, develop and maintain SQL Server Reporting Services reports </br>
      •	Database design and development with SQLServer 2012/2014/2017 </br>
      •	AWS based Cloud Architecture and migration skills and experience, currently working in cross domains migration in the cloud. </br>
      •	Coordinated with the Project Management, Development and QA Team in resolving any configuration and deployment issues, and to provide smooth release process. </br>
      •	Responsible for managing Code Repository in TFS 2013/2015/2017. </br>
      •	Work with continuous Integration and Continuous deployment pipeline (CI/CD) using VSTS. </br>
      •	Set technical standards and practices, including technical design and review process, coding standards, and code reviews. </br>
      •	Identified complex business problems and resolved technical issues. </br>
      •	Regularly communicates the status of application development to all impacted stakeholders, set expectations and manage team members </br>
      •	Strong working knowledge of management principles in order to mentor and lead staff toward the successful completion of assignments </br>
      •	Expertise and strength in hiring, leading and growing talent within teams, and help build vision that facilities organizational growth. </br> 

 - title: Application Development Supervisor
   start: 2016
   end: 2018
   employer: DSHS
   description: DSHS Children's Administration is the public child welfare agency for the state of Washington. As an IT Supervisor, 
    this position specializes in supporting the mission-critical applications that support CA’s vision of ending child abuse and
    neglect. </br>
    •	Provide line management and development of a team of 10 software developers. </br>
    •	Lead all efforts surrounding DSHS Children’s Administration designing, develop, implements complex software applications and test changes to application subsystems. </br>
    •	Responsible to work with improvements, by participation in the development, of the architectural principles, processes and standards </br>
    •	Mentor and monitor the work of others to ensure development standards in design and technique is followed and technical documentation is prepared </br>
    •	Acted as lead decision maker on final incident resolution of application issues </br>
    •	Prioritize and manage workload to meet deadlines. Ensure timelines, expectations, and deliverables and that the team(s) involved are held accountable to these expectations </br>
    •	Manage day to day performance and operation of the development team </br>
    •	Coordinate acceptance testing with partners of modified programs, analyzing test results to ensure accuracy and completeness </br>
    •	Perform periodic and annual performance reviews for all team members. </br>
    •	Develop performance improvement plans for team members who have performance issues </br>  
 
 - title: Lead Software Developer
   start: 2015
   end: 2016
   employer: DSHS
   description: This role required strong development expertise, domain proficiency, platform depth, and leadership. Project highlights
      included </br>
    •	FamLink – 24x7 Washington’s statewide automated child welfare system serving approximately 2600 social workers and staff, and 
      tracking approximately 200,000 families within the system. As a lead software developer, I am responsible for the maintenance of
      the system and data fixes.  Many changes being legislatively driven must be implemented within a certain amount of time. </br>
    •	FamLink Pro – Enhancement project providing responsive technologies to the FamLink system.
      Starting with the Child Health & Education Tracking (CHET) module and using the agile scrum development methodology, 
      this position is responsible to build the system from scratch in a responsive web design application to serve as a model for
      the rest of the new system to replace the FamLink system. CHET will be able to assign cases to social workers and supervisors
      who can then work on their cases and save their work online and offline The CHET program is divided into five different 
      domains. Technologies used to develop this software include .NET MVC, Owin authentication, Restful Web Apis, Entity Framework,
      SQL Queries, C#, Stored Procedures, Ajax, JQuery, AngularJS, front end technologies Bootstrap, CSS, Html, Razor. </br>
    •	Discovery Tool – Led a team of software developers in an agile environment to develop and design a new software application named
      Discovery Tool to help social workers find cases in different databases using advanced searchable interfaces. The application 
      generates dynamic online views for desktop and mobile devices and generates reports using SSRS. Technologies used to develop 
      this application included .NET MVC, Restful Web Apis, Entity Framework, C#, Stored Procedures, SQL Server, Log4NET, TFS,
      Bootstrap, Razor, JavaScript, Ajax, JQuery. </br>
    •	Employee Directory – Developed an employee directory for DSHS Children’s Administration to provide a searchable interface of
      current employees. The source of the information is from Microsoft Active Directory. Technologies using to develop this 
      application included a responsive web design, .NET MVC, Bootstrap, C#, SOAP, EF, JQuery, SQL Stored Procedures. </br>
    •	Foster Parent Portal – Developed a portal for foster parents to register and download our mobile foster kid application created
      in Xamarin. Through the registration, the system creates a new account in MassS360 Mobile device management. Technologies using
      to develop this application included a responsive web design, RESTful APIs, .NET MVC, Entity Framework, Bootstrap, C#, Ajax, 
      JQuery, SQL. </br>
      In all projects </br>
    •	Worked collaboratively with business analysts, solution leads, database administrators, testers and architects to design, 
      develop, test and implement applications using .NET technologies. </br>
    •	Performed all aspects of the software development life-cycle including analysis, planning, design, development, testing, quality
      assurance, deployment, maintenance, troubleshooting and/or problem resolution tasks of complex business web-based applications
      using .NET technologies, responsive web design patterns and SQL Server. </br>
    •	All these projects were created fully in-house saving millions of dollars of taxpayers </br>

 - title: Senior Software Developer
   start: 2011
   end: 2014
   employer: MRSC
   description: Developed, maintained, and tested new and or existing web-based applications and database systems. Coordinated designed
       and implemented applications, collaborating with project managers and stakeholders to ensure on-time completion of project 
       deliverables. Developed overall project architecture and database. Designed Web applications and maintained content for .NET 
       based systems</br>   
     •	In charge of the mission’s entire in-house software development. </br>
     •	Front-end development utilizing HTML5, CSS3 and JavaScript leveraging the Bootstrap framework and a .NET / SQL backend. </br>
     •	Led the design, development and testing for the e-commerce website for the MRSC Publications using ASP.NET, C#, SQL Server, HTML, 
       Adobe Photoshop, CSS, JavaScript and CyberSource APIs to secure online transactions. </br>
     •	Designed and developed a full responsive intranet page for the use of the employees. </br>
     •	Led a team to redesign and iterate user experience by designing and implementing new modules and interfaces in a complex, 
       responsive site. www.mrsc.org/home.aspx </br>
     •	Developed and designed a database search page using ASP.NET, C#, SQL Server, JavaScript, Ajax, HTML and other front end and
       middle-tire technologies. The page includes different search criteria to find election results for all the cities, counties and 
       jurisdictions in the state of Washington. </br>
     •	Redesigned and implemented a new database for the MRSC rosters based on new business requirements. The roster is an online shared 
       database service hosting individual agency business list/application. This project involved working with SQL Server, T-SQL and 
       queries to create, combine, delete, update and data migration to the new database. www.mrscrosters.org </br>
     •	Responsible for migrating registration pages to RegOnline using Web APIs, Windows Communication Foundation, ASP.NET, XML, C#. </br>
   
 - title: Software Developer
   start: 2007
   end: 2010
   employer: EHB Digital
   description: Worked as a software developer for IT staffing agencies and freelance IT consultant to help businesses in analyzing, implementing and evaluating IT projects to meet performance expectations.
       Ability to explain complex technical issues in a non-technical manner </br>
       •	Involved in gathering the requirements, analysis, design and development of the project. </br>
       •	HTML / CSS / JavaScript, JAVA, C#, PHP backend and MySQL for dynamic database driven websites, WordPress and Drupal front-end development for dynamic database-driven websites. </br>
       •	Developed wireframes, interface mockups and page prototypes </br>
       •	Maintained consistency and compatibility of UX across browsers and services </br>
       •	Developed RFP responses, proposals and cost estimates. </br>
       
 - title: Application Developer
   start: 2003
   end: 2007
   employer: US Bank
   description: •	Participate in designing, coding, testing, implementation and documentation of solutions. </br>
       •	Develop, test, implement and support of application systems. </br>
       •	Participate in the definition of project tasks. </br>
       •	Participate in investigation, analysis, and resolution of technical problems related to system functions, programming and procedures </br>
       •	Performed unit testing, system testing and user acceptance test. </br>
       •	Software development support for enhancement of Web applications accessed by 12 million users. </br>
         Technology used in all projects HTML, CSS, JavaScript, XML, C#, .NET, SQL Server </br>
  
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2012
   subject: Information System Management 
   school: City University of Seattle
   
 - level: Bachelor of Science (B.Sc.)
   date: 2008
   subject: Computer and Software Systems 
   school: University of Washington
   
 - level: Associate of Science (A.S.)
   date: 2006
   subject: Computer Science
   school: Renton Technical College

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/5d9d2f5af8b6f152c7f415081146da7e
   courses:
    - title: Agile Planning for Software Products
      link: https://www.coursera.org/learn/agile-planning-for-software-products
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: May 21, 2019
    - title: Client Needs and Software Requirements
      link: https://www.coursera.org/learn/client-needs-and-software-requirements
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2019
    - title: Software Processes and Agile Practices
      link: https://www.coursera.org/learn/software-processes-and-agile-practices
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: March 19, 2019
    - title: Continuous Delivery & DevOps
      link: https://www.coursera.org/learn/uva-darden-continous-delivery-devops
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: March 24, 2019

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:


#List of interesting Github repo/projects to include - optional
github:
 - edwinhere72/NorthwindTraderProject
 - edwinhere72/MyLinkedList
 
 
#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: https://stackoverflow.com/users/258813/rhinds
#   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: 
  Solution Architect and Full-stack developer with leading experience. Expertise in all phases of software development with an in-depth
  knowledge of architecture, agile methodologies, design patterns and object-oriented principles. Passionate about building applications
  from the ground up, enhancing existing systems for sustainability or meeting business needs through integration purposes. </br> </br>
  •	More than 18 years of software development experience. </br>
  •	7 years management experience leading software engineering teams. </br>
  •	Ability to direct complex Software Projects from concept to fully operational status. </br>
  •	Effective communicator, goal-oriented individual with strong leadership capabilities. </br>
  •	Well organized, highly motived, and detail-oriented problem solver </br>

  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
