# Site settings
title: Edwin Heredia
twitter_username: 
name: Edwin Heredia

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://automateddeveloper.blogspot.com/
 - title: GitHub
   url: https://github.com/edwinhere72
 - title: StackOverflow
   url: https://stackoverflow.com/users/258813/rhinds
 - title: DZone
   url: https://dzone.com/users/899489/rhinds.html
 - title: LinkedIn
   url: https://www.linkedin.com/in/edwin-heredia-3029b819/

#Any buzzword skills you want to include
skills:
 - C#
 - ASP.NET MVC
 - .NET technology
 - Entity Framework
 - Restful Web Apis
 - WCF
 - SOAP
 - HTML5
 - CSS3
 - Bootstrap
 - JavaScript
 - Angular JS
 - Node JS
 - React JS
 - Java
 - PHP
 - SQL Server
 - Database Design
 - DevOps CI/CD
 - AWS
 - Azure 
 - Docker 
 - Kubernetes
#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Application Development Supervisor
   start: 2018
   end: Ongoing
   employer: DCYF
   description: Currently leading 10 software developers that includes 3 agile development teams. <br/>
   <ul>
   <li>	Provide technical leadership to the development team of agile software developers to create, maintain, and enhance diverse 
        software application system.</li>
   <li>Work closely with the Product/Business teams in defining the software development plan in meeting the product vision </li>
   <li>Coordinate with various business units and determined priority for projects and analyzed resources required.</li>
   <li>Ability to build prototype software using modern programming language such as C#, .NET MVC, Entity Framework, Java, JavaScript,
       JQuery, Bootstrap.</li>
   <li>Design, develop, and maintain full-stack web applications on AWS; heavy focus on RESTful APIs with automate deployment DevOps 
       using TFS, Octopus Deploy, Redgate SQL for Database.</li>
   <li>Design, develop and maintain SQL Server Reporting Services reports </li>
   <li>Database design and development with SQLServer 2012/2014/2017 </li>
   <li>AWS based Cloud Architecture and migration skills and experience, currently working in cross domains migration in the cloud.</li>
   <li>Coordinated with the Project Management, Development and QA Team in resolving any configuration and deployment issues, and to 
       provide smooth release process.<li>
   <li>Responsible for managing Code Repository in TFS 2013/2015/2017.<li>
   <li>Work with continuous Integration and Continuous deployment pipeline (CI/CD) using VSTS.<li>
   <li>Set technical standards and practices, including technical design and review process, coding standards, and code reviews.<li>
   <li>Identified complex business problems and resolved technical issues.<li>
   <li>Regularly communicates the status of application development to all impacted stakeholders, set expectations and manage team members<br/>
   <li>Strong working knowledge of management principles in order to mentor and lead staff toward the successful completion of assignments<br/>
   <li>Expertise and strength in hiring, leading and growing talent within teams, and help build vision that facilities organizational growth. <br/>
   
 - title: Application Development Supervisor
   start: 2016
   end: 2018
   employer: DSHS
   description: DSHS Children's Administration is the public child welfare agency for the state of Washington. As an IT Supervisor, this position specializes in supporting the mission-critical applications that support CA’s vision of ending child abuse and neglect. 
   •	Provide line management and development of a team of 10 software developers. 
   •	Lead all efforts surrounding DSHS Children’s Administration designing, develop, implements complex software applications and test changes to application subsystems. 
   •	Responsible to work with improvements, by participation in the development, of the architectural principles, processes and standards
   •	Mentor and monitor the work of others to ensure development standards in design and technique is followed and technical documentation is prepared
   •	Acted as lead decision maker on final incident resolution of application issues
   •	Prioritize and manage workload to meet deadlines. Ensure timelines, expectations, and deliverables and that the team(s) involved are held accountable to these expectations
   •	Manage day to day performance and operation of the development team
   •	Coordinate acceptance testing with partners of modified programs, analyzing test results to ensure accuracy and completeness
   •	Perform periodic and annual performance reviews for all team members. 
   •	Develop performance improvement plans for team members who have performance issues
 
 - title: Lead Software Developer
   start: 2015
   end: 2016
   employer: DSHS
   description: Covestor is an investment marketplace startup that was successfully acquired by Interactive Brokers in 2015. <br/> Working as a senior engineer, I worked closely with the CTO and across the full-stack, I was involved in all aspects of the technology including the website and back-end services.
 - title: Associate Manager
   start: 2005
   end: 2012
   employer: Accenture
   description: Working on a range of functional and technical roles, primarily working on client sites in Financial Services in London and Europe.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 
#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/258813/rhinds
   flairimageurl: https://stackoverflow.com/users/flair/258813.png

intro: 
  Solution Architect and Full-stack developer with leading experience. Expertise in all phases of software development with an in-depth knowledge of architecture, agile methodologies, design patterns and object-oriented principles. Passionate about building applications from the ground up, enhancing existing systems for sustainability or meeting business needs through integration purposes. 
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: My current role uses Scala as the primary language and have been building applications in Scala for the last two years. I am familiar with a range of Scala libraries, such as <a target="_blank" href="https://automateddeveloper.blogspot.com/2017/12/an-opinionated-guide-to-building-apis.html"> Akka-Http for building microservices</a> and <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/09/generic-programming-with-scala.html"> Shapeless for generic programming</a>, as well as familiar with a range of <a target="_blank" href="https://basementcrowd.com/2018/11/28/scala-the-aux-pattern-path-dependent-types/" >functional programming techniques available</a>.<br/><br/>
   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)
